#!/usr/bin/env python3
"""
Print the league's derived numbers as markdown, ready to paste into the docs.

This exists because the figures in league_lore.md and owner_deep_dive.md were
hand-copied out of a script run months ago, and hand-copied numbers rot. When
the optimal-lineup solver was corrected, every efficiency figure in those
documents became wrong at once and nothing announced it.

Run this and paste the output. Better, run it on the same machine that holds
the player cache, because without players_nfl.json the position map falls back
to a conservative guess, the optimal is understated, and every efficiency
figure printed here is a lower bound rather than the answer. The script says so
loudly if the cache is missing.

    python3 league_numbers.py --data sleeper_history
    python3 league_numbers.py --data sleeper_history --seasons 2023 2024 2025
"""

import argparse
import collections
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import lineup_efficiency as LE

# The documents use given names; Sleeper uses handles. Mapping them here keeps
# the pasted table in the voice the documents are written in.
FRIENDLY = {
    "Denk0": "Denk",
    "natergater24": "Nate",
    "cj21k": "Chris",
    "aleksthebrun": "Cunado",
    "Naughtynun": "Lucas",
    "GregoryOdensKnees": "Johnny",
    "goatnasty": "Billy",
    "gilbertb12": "Ben",
    "wiggitywakes": "Brendan",
    "mcryns14": "Max",
}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data", required=True)
    ap.add_argument("--seasons", nargs="+")
    a = ap.parse_args()

    cache = os.path.join(a.data, "players_nfl.json")
    have_cache = os.path.exists(cache)

    years = a.seasons or LE.seasons(a.data)
    pos, names, _ = LE.build_positions(a.data, years)
    rows = LE.analyse(a.data, years, pos, names, quiet=True)

    agg = collections.defaultdict(lambda: [0.0, 0.0, 0, 0])
    for (o, y), v in rows.items():
        agg[o][0] += v["actual"]
        agg[o][1] += v["optimal"]
        agg[o][2] += v["flips"]
        agg[o][3] += v["weeks"]

    print()
    if not have_cache:
        print("!! players_nfl.json is NOT present in " + a.data)
        print("!! Every figure below is a LOWER BOUND, not the answer.")
        print("!! Do not paste this into a document. Run pull_players.py first.")
        print()
    print(f"Seasons: {', '.join(sorted(years))}")
    print(f"Player cache: {'present' if have_cache else 'MISSING'}")
    print()

    # --- the league table, in the documents' own column order ---------------
    print("## League table, efficiency and flips")
    print()
    print("| Owner | Lineup eff | Flips |")
    print("|---|---|---|")
    order = sorted(agg, key=lambda o: -(agg[o][0] / agg[o][1]) if agg[o][1] else 0)
    for o in order:
        a0, o0, f, _ = agg[o]
        eff = 100 * a0 / o0 if o0 else 0
        print(f"| {FRIENDLY.get(o, o)} | {eff:.1f}% | {f} |")
    print()

    best = order[0]
    second = order[1]
    most_flips = max(agg, key=lambda o: agg[o][2])
    fewest_flips = min(agg, key=lambda o: agg[o][2])
    print("## Sentences the documents assert, restated from current data")
    print()
    print(f"- Best lineup efficiency: **{FRIENDLY.get(best, best)}**, "
          f"{100 * agg[best][0] / agg[best][1]:.1f}%")
    print(f"- Second: **{FRIENDLY.get(second, second)}**, "
          f"{100 * agg[second][0] / agg[second][1]:.1f}%")
    print(f"- Most flips: **{FRIENDLY.get(most_flips, most_flips)}**, "
          f"{agg[most_flips][2]}")
    print(f"- Fewest flips: **{FRIENDLY.get(fewest_flips, fewest_flips)}**, "
          f"{agg[fewest_flips][2]}")
    print()

    # --- per season, because single-season claims live in the profiles ------
    print("## By season")
    print()
    print("| Owner | Season | Actual | Optimal | Left | Eff | Flips |")
    print("|---|---|---|---|---|---|---|")
    for (o, y), v in sorted(rows.items(), key=lambda x: (x[0][0], x[0][1])):
        eff = 100 * v["actual"] / v["optimal"] if v["optimal"] else 0
        print(f"| {FRIENDLY.get(o, o)} | {y} | {v['actual']:.1f} | "
              f"{v['optimal']:.1f} | {v['optimal'] - v['actual']:.1f} | "
              f"{eff:.1f}% | {v['flips']} |")
    print()
    print("Generated by league_numbers.py. Any figure in a document that "
          "disagrees with this table is stale, not disputed.")


if __name__ == "__main__":
    main()
